# linode gluster ansible playbook

# cluster pre-check
- name: pre-check
  hosts: gluster_servers
  user: root
  vars_files:
    - group_vars/gluster/vars
    - group_vars/gluster/secret_vars
  
  roles:
    - precheck

# ssl certs
- name: generate ssl certs
  hosts: localhost
  vars_files:
    - group_vars/gluster/vars
  
  roles:
    - tls

# gluster servers
- name: configure gluster servers
  hosts: gluster_servers
  user: root
  vars_files:
    - group_vars/gluster/vars
    - group_vars/gluster/secret_vars
  
  roles:
    - common
    - gluster

# client servers
- name: configure gluster clients
  hosts: client_servers
  user: root
  vars_files:
    - group_vars/gluster/vars
    - group_vars/gluster/secret_vars
  
  roles:
    - common
    - client